# Define the TOP_DIR path
export TOP_DIR = $(abspath $(PWD)/../..)

export OVERRIDE_SUBMODULE_LOCKS = 1

# Use top level makefile
include ../shared_version.mk
include $(TOP_DIR)/submodules/ruckus/system_vivado.mk
